### ISSUE TITLE
Optimize CVA C++ build

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-platform-demos#19]
The `banking/credit-value-adjustment/cva-cpp` build is too resource intensive (time and space) - it compiles gRPC and QuantLib libraries everytime.
Use pre-compiled binaries if possible.

I've tried to configure a GitHub Actions workflow for the project, but the build fails (after ~90min) with:
```
[INFO] error writing '/usr/local/lib/libQuantLib.a': No space left on device
```

This was the workflow used (`.github/workflows/pr_builder.yml`):
```yml

name: PR Builder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B  -U clean install -Prelease
```
